remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: Lindsey Smith's Professional Portfolio
description: A showcase of my software development projects, skills, and my professional background.
